### ISSUE TITLE
Cannot find nearest Crownstones

### ISSUE THREAD

**Issue by notredamstra** [dobots/crownstone-app#6]
Hi guys,

Using the Cordova app in this repository I cannot find any Crownstones nearby. While using the older app from the Android Play Store I do find all the nearest Crownstones.

I didn' t touch any settings or files whatsoever. Any idea what might be causing this?

**Comment by vliedel** [comment]
Hi, what exactly do you mean with "find crownstones nearby"?
I noticed the current code has the hub page as start page, which shouldn't be the case, we will soon make a commit to revert that.

**Comment by notredamstra** [comment]
I mean that when I press the 'Scan' button to scan for Crownstones in range it does not find any Crownstones. And when I do the exact same thing in the older version of the app from the Play Store it does find my Crownstone.

**Comment by eggerdo** [comment]
It could be an issue with old plugins / software versions. Try to update cordova and the plugins:

1. Update cordova: `npm install -g cordova`
2. Make sure you have Android 5.1.1 (API 22) installed 
3. Goto scripts folder and run `./update_cordova.sh`
4. in the scripts folder, run `./fix_name.sh`
5. `cordova run android`

Does it work now?

**Comment by notredamstra** [comment]
I will test that later this evening, thanks. I'll let you know if it works :+1:

**Comment by eggerdo** [comment]
Nothing heard anymore, closing it, open again if it happens again
